apiVersion: v1
kind: Service
metadata:
   name: jenkins-service
spec:
  type: NodePort
  selector:
    app: pradeep
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
      nodePort: 30078
