apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-lable
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-lable
  ports:
    - protocol: TCP
port: 8087
targetPort: 80
nodePort: 30098
